### ISSUE TITLE
Sublime 3 (fresh and old instalation) expand_fqcn and goto_definition_scope don't work

### ISSUE THREAD

**Issue by leandromatos** [erichard/SublimePHPCompanion#80] opened 2016-07-08 23:28 UTC
I've been trying to use expand_fqcn and goto_definition_scope for a few days. I've tried to disable all plugins and it still doesn't work. I've also tried to use a new installation without plugins without success. Anyone else has had this problem?

**Comment by phppirate** [comment] 2016-07-23 21:05
Yes, I have this problem as well.

I had switched back to Sublime after being a long time PHP Storm user, but because this feature has stopped working I am back to Storm.

Really hoping this gets fixed soon.

**Comment by iamanders** [comment] 2016-07-26 07:12
Duplicate of #76 ?

**Comment by leandromatos** [comment] 2016-07-26 15:50
Yes, this issue was opened after #76 closed.

As the problem there was not solved, I opened this issue again, but, a few days they opened #76.

**Comment by erichard** [comment] 2016-07-26 15:51
I close this one as duplicate

**Closed by erichard** 2016-07-26 15:51 UTC
Labels: duplicate
