### ISSUE TITLE
import_namespace_command doesn't work in sublime text build 4121

### ISSUE THREAD

**Issue by TZSoe** [erichard/SublimePHPCompanion#146] opened 2021-11-20 09:43 UTC
When I run my import_namespace_command shortcut from key bindings ,the python console shows this error

![error](https://user-images.githubusercontent.com/39611545/142721714-957d8fd1-9c91-4758-abf6-426e3e7d04ad.png)

**Comment by lessandsass** [comment] 2022-01-01 16:10
Yeah. Me too. not only for version 4121 and above versions too

**Comment by erichard** [comment] 2022-01-24 09:35
I'm able to reproduce the error but it does not appear all the time. And when the error pop, the command still works. Seems to be related to saving. The only way I've found to get the error all the time is to trigger the command when a file has recently be saved. Very strange. 

I will check the sublime changelog to see if anything as change.

**Comment by cvetan** [comment] 2022-02-19 08:34
What's weird is that if you put cursor on class you want to import and trigger find use command, the namespace gets imported.

**Comment by jesephan** [comment] 2022-03-14 15:51
Any updates on this issue? I'm having the same problem with this package installing it to sublimetext 4 build 4126.

**Comment by jesephan** [comment] 2022-03-27 00:11
> No update at the moment. I'm not able to reproduce the error. My previous comment is in fact a different error message.
> 
> Maybe it is a platform specific issue. Which OS do you all use ?

I'm using mac os montery 12.2.1

**Comment by cvetan** [comment] 2022-03-28 00:44
I am using mac os big sur 11.6.5 and Ubuntu 20.04

**Comment by wotek** [comment] 2022-04-01 06:13
I think I got a case where you can reproduce the error.

Consider following project structure:

```
❯ tree
.
├── composer.json
├── src
│   ├── Bar.php
│   └── SubFolder
│       └── Foo.php
└── vendor
    ├── autoload.php
    └── composer
        ├── ClassLoader.php
        ├── LICENSE
        ├── autoload_classmap.php
        ├── autoload_namespaces.php
        ├── autoload_psr4.php
        ├── autoload_real.php
        └── autoload_static.php
```

`composer.json`:

```json
{
  "name": "wotek/php-companion-issue",
  "autoload": {
    "psr-4": {
      "Namespace\\": "src/"
    }
  },
  "require": {}
}
```

If you run import namespace command while editing `Foo.php` it works just fine.
However for `Bar.php` it doesn't work - looks like it has problem with root level project files?

**Comment by mastir** [comment] 2022-04-13 14:26
its broken for all projects witout composer.json in root folder, i made fix for this issue in sublime3 https://github.com/erichard/SublimePHPCompanion/pull/135 but as i see somthing changed in folder structure probably this path must be fixed. Folder "/home/eugn/.config/sublime-text/Packages/PHP Companion" doesn`t exist, coping composer.json  to this path fixed import_namespace command. I will try to solve this on weekend. 
```
Traceback (most recent call last):
  File "/snap/sublime-text/112/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/home/eugn/.config/sublime-text/Installed Packages/PHP Companion.sublime-package/php_companion/commands/import_namespace_command.py", line 22, in run
  File "/home/eugn/.config/sublime-text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 84, in get_namespace
  File "/home/eugn/.config/sublime-text/Installed Packages/PHP Companion.sublime-package/php_companion/utils.py", line 81, in get_composer
FileNotFoundError: [Errno 2] No such file or directory: '/home/eugn/.config/sublime-text/Packages/PHP Companion/composer.json'
```

**Comment by cvetan** [comment] 2022-06-19 09:57
Any update on this?

**Closed** 2022-06-23 15:39 UTC

**Comment by dzgrief** [comment] 2022-07-14 08:36
I have the same problem.  The command line prompts no command for selector: noop:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7501701/178939436-a06413f6-6bdd-4c81-a3fc-b6ee1af2c8e8.png">

mac OS Monterey 12.4
Sublime Text 4126
PHPCompanion v2.0.3

**Comment by dzgrief** [comment] 2022-07-14 09:02
<img width="792" alt="image" src="https://user-images.githubusercontent.com/7501701/178945152-fa40dbfd-ead4-4fb5-a636-754cb144099f.png">

I set up shortcut keys. It worked.
