### ISSUE TITLE
Only import_namspace and constructor parameters are working

### ISSUE THREAD

**Issue by keevitaja** [erichard/SublimePHPCompanion#85] opened 2016-09-14 20:24 UTC
Hi.

I have a strange issue. Only impost_namespace and insert_php_constructor_property are working.

These are my key bindings:

```
    { "keys": ["f6"], "command": "expand_fqcn" },
    { "keys": ["shift+f6"], "command": "expand_fqcn", "args": {"leading_separator": true} },
    { "keys": ["f5"], "command": "find_use" },
    { "keys": ["f4"], "command": "import_namespace" },
    { "keys": ["f3"], "command": "implement" },
    { "keys": ["shift+f12"], "command": "goto_definition_scope" },
    { "keys": ["f7"], "command": "insert_php_constructor_property" },
```

Any idea how to fix this?

**Comment by gmask** [comment] 2016-09-16 18:01
Same here.

**Comment by keevitaja** [comment] 2016-09-16 19:16
@gmask something weird has happened. My solution was to remove(backup before) sublime config directory, start sublime (it will recreate the directory) and then take user stuff (conf, snippets, macros etc) from old directory and reinstall packages.

**Comment by erichard** [comment] 2016-09-19 14:27
Look like a problem with the sublime index and a duplicate of #76. 

I close this one.

**Closed by erichard** 2016-09-19 14:27 UTC
